### PR TITLE
Add note about triggering onChange with a different value

### PR DESCRIPTION
**Pull request by silvenon**
**What**: I added an explanation and an example how to trigger the `onChange` handler with `fireEvent`:

```js
const comment = getByLabelText('Comment')
comment.value = 'Great advice, I love your posts!'
fireEvent.change(comment)
```

**Why**: I didn't know how to do this because I was so used to `Simulate`, it took me a while to figure it out. I'm not 100% sure if this is the "right" way to do it, someone please correct me if it's not.

**Checklist**:

- [x] Documentation
- [ ] Tests (N/A)
- [x] Ready to be merged
      
- [x] Added myself to contributors table
      

This PR references #66.

### CODE REVIEW

**Comment by kelly-tock** [comment]
found this after trying to figure out a form test, I noticed when you fire change, only the `target` property of event is fired and not `currentTarget`, 

example:
```
<input onChange={this.handleChange} value={value} data-testid="input" />
```

const input = getByTestId('input');

 input.value = 'testing';

 fireEvent.change(
    input
 );
```

in the change handler, target is defined but not current target. 

any ideas?

**Comment by kelly-tock** [comment]
also as an example, if you're using flowtype or typescript, 

```
handleChange(event: React.SyntheticEvent<HTMLInputElement>) {
    const value = event.currentTarget.value;
```

works, but target does not.

**Comment by kentcdodds** [comment]
That could be a bug with dom-testing-library. Care to file that?

**Comment by kelly-tock** [comment]
cool, i'll file it.

**Comment by kelly-tock** [comment]
https://github.com/kentcdodds/dom-testing-library/issues/73

**Pull request merged**
