### PR TITLE
findBy* for #345

### LINKED ISSUE #345: findBy* and waitForElement* not returning HTMLElement anymore (since 6.1.0) (works in dom-testing-library)
- `react-testing-library` version: 6.1.x
- `react` version: ^16.8.3
- `node` version: 10.15.x
- `npm` (or `yarn`) version: 6.9.0

### Relevant code or config:
The following test fails in react-testing-library
```jsx
test('findByTestId returns the element', async () => {
  const ref = React.createRef()
  const {findByTestId, getByTestId} = render(
    <div ref={ref} data-testid="foo" />,
  )
  await expect(findByTestId('foo')).resolves.toEqual(getByTestId('foo'))
})
```

While the following test passes in dom-testing-library
```js
test('waits for element to appear in a specified container', async () => {
  const {rerender, container, getByTestId} = render('<div />')
  const promise = waitForElement(() => getByTestId('div'), {container})
  setTimeout(() => rerender('<div data-testid="div" />'))
  const element = await promise
  expect(element).toEqual(getByTestId('div'))
})
```

### What you did:

I was trying to use the `findByTestId` API to grab an element. 

### What happened:

The resolved value is undefined in react-testing-library 6.1.x but returns fine in 6.0.0. 

### Reproduction:

See the above scenarios above.

### Problem description:

Code that used to leverage the elements returned by findBy* and waitFor* will now start to fail.

### Suggested solution:

I suspect this has to do with the recent asyncWrapper addition, which is set to `cb => cb()` in DTL but likely something that doesn't return the value in RTL.

### LINKED ISSUE #347: waitForElement not working as expect on latest react version(16.8.6)
- `react-testing-library` version: 6.1.1
- `react` version: 16.8.6
- `node` version: 11.10.1
- `yarn` version: 1.13.0
- `jest-dom` version: 3.1.3

### What you did:

Just run ```yarn create react-app from-scratch --typescript```
Add the ```react-testing-library``` and ```jest-dom``` to the package.json, update the ```App.test.tsx``` with:

```js
import React from 'react';
import {render, waitForElement } from 'react-testing-library'
import 'jest-dom/extend-expect'

test('tests', async () => {
  const { getByTestId } = render(
    <div data-testid='error'>something</div>
  );

  const something = await waitForElement(() => getByTestId('error'))
  expect(something).toHaveTextContent('something')
})

```

### What happened:

Screen Shot 2019-04-05 at 3 36 58 PM

### Reproduction:
[code sandbox](https://codesandbox.io/embed/pj04w2434m)

### Problem description:

The tests pass if I downgrade to:
```json
    "react": "16.8.1",
    "react-dom": "16.8.1",,
    "react-testing-library": "5.5.3",
    "jest-dom": "3.0.0"
```

### Suggested solution:

I'm starting the bisect from the versions to see what might be changed.

### PR DESCRIPTION
**Pull request by joual**
**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/alexkrolick/testing-library-docs)
- [ ] Tests
- [ ] Typescript definitions updated
- [ ] Ready to be merged
      

Closes #345 
Closes #347

### CODE REVIEW

**Comment by kentcdodds** [comment]
This actually isn't enough to fix it for 16.9.0 unfortunately. I'll go ahead and pull this PR and work on it a bit more. Thanks!

**Comment by joual** [comment]
Ya I figured, and you might want to put the test somewhere that makes more sense or massage it into something that might detect all the cases you need :)

**Comment by joual** [comment]
Thank you for all your work!

**Comment by kentcdodds** [comment]
Oh, let's keep this open. I'll just update your PR :)

**Comment by kentcdodds** [comment]
@allcontributors[bot], please add @joual for bug, test, and code

**Pull request merged**
