### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarkPollmann**
**What**:
Small grammatical fix

**Why**:
Superior readability :)

**How**:
N/A

**Checklist**:

* [x] Documentation
* [ ] Tests N/A
* [x] Ready to be merged 
* [ ] Added myself to contributors table  N/A

### CODE REVIEW

**Comment by antoaravinth** [comment]
This looks good to me.

**Comment by kentcdodds** [comment]
Thank you!

**Comment by kentcdodds** [comment]
Would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)?

**Pull request merged**
