### PR TITLE
Fixes types

### LINKED ISSUE #81: TypeScript fails: A type literal property cannot have an initializer
* `react-testing-library` version: 3.0.1
* `react` version: 16.3.2
* `node` version: 8.11.1
* `npm` version: 5.6.0
* `TypeScript` version: 2.8.3

It seems like there is a problem with the typings for TypeScript. If I'm import the library and try to compile TypeScript fails.

```ts
import {  } from 'react-testing-library';
```

```
/home/node/app/client/node_modules/react-testing-library/typings/index.d.ts
(6,21): A type literal property cannot have an initializer.
```

### PR DESCRIPTION
**Pull request by InExtremaRes**
Fixes #81 

**What**: Fixes typings for TypeScript.

**Why**: The syntax wasn't correct and TypeScript didn't compile.

**How**: Removing the initializers

**Checklist**:

* [ ] Documentation
* [x] Tests
* [x] Ready to be merged 
* [x] Added myself to contributors table

### CODE REVIEW

**Comment by maddijoyce** [comment]
Ah good catch. I don’t know I didn’t spot those in the update.

**Comment by kentcdodds** [comment]
Hmmm... You'll need to resolve the `.all-contributorsrc` conflicts, then run `npx kcd-scripts contributors generate` and that'll fix the README.

**Comment by InExtremaRes** [comment]
Is it ok if I rebase the master branch and push again?

**Pull request merged**
