### PR TITLE
fix(TS): Add missing getAll and queryAll functions to TS definitions

### PR DESCRIPTION
**Pull request by pbomb**
**What**:

Adds missing TypeScript definitions for the getAll* and queryAll* functions. Also adds type definition for re-exported `getQueriesForElement` function.

**Why**:

These additions more accurately reflect what the library does and they're helpful. I found that I could get rid of some calls to `querySelectorAll` in favor of `queryAllByTestId` in my tests, which was more convenient.

**How**:

Imported and reused the TS definitions from dom-testing-library to bind the get/query functions to the dom element.

**Checklist**:

* [x] Documentation
* [x] Tests
* [x] Ready to be merged 
* [x] Added myself to contributors table

### CODE REVIEW

**Comment by pbomb** [comment]
Thanks, Kent!

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by pbomb** [comment]
Thanks again!

**Pull request merged**
