### PR TITLE
 README: Add render options Example for container

### PR DESCRIPTION
**Pull request by duncanleung**
_Aside: Thank you for this library! I really really enjoy the API and testing philosophy behind it. Also, I really enjoyed your "Testing React Applications" workshop on Front End Masters!_

_I'm still very new to testing, so I hope that my README example makes sense. Open to all feedback! Thank you!_

**What**:
README: Add `render` options example for `container`.

**Why**:
I was unit testing a `tablebody` element, and got a `validateDOMNesting` error because:
> By default, `react-testing-library` will create a `div` and append that `div` to the `document.body` and this is where your react component will be rendered.

```javascript
Warning: validateDOMNesting(...): <tbody> cannot appear as a child of <div>.
    in tbody (created by TableBody)
    in TableBody (created by TableBody)
    in TableBody
```
It was not straight forward for me to find out how to use the `options` parameter in the `render()` method.

I think it will be helpful to add an example to the README.

**How**:
My original unit-test was:

```javascript
import React from "react";
import { render, cleanup, fireEvent } from "react-testing-library";

import TableBody from "../TableBody";
import listingDataMock from "../__mocks__/TableBody-listing-data";

afterEach(cleanup);

describe("TableBody", () => {
  test("Snapshot", () => {
    //Arrange--------------
    const listingData = listingDataMock;
    const tableBodyKey = "candidateId";

    const props = {
      listingData,
      tableBodyKey
    };

    const { container } = render(<TableBody {...props} />);

    //Assert---------------
    expect(container).toMatchSnapshot();
  });
});
```

**Checklist**:

- [x] Documentation
- [ ] Tests
- [x] Ready to be merged
      
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by kentcdodds** [comment]
Would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)?

**Comment by duncanleung** [comment]
Sure! Thank you!

I guess I have to do this with another PR since this one is merged already?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kentcdodds** [comment]
Yep 👍

**Pull request merged**
