### PR TITLE
wrapper for testHook

### PR DESCRIPTION
**Pull request by FredyC**
**What**:

Implementation of #293 based on discussion in #283.

**Why**:

To allow specifying a wrapper component tree around the testHook tree.

```jsx
  testHook(callback, {
    wrapper: props => (
      <NameContext.Provider value={nameValue}>
        <OtherContext.Provider value={otherValue} {...props} />
      </NameContext.Provider>
    )
  })
```

**Checklist**:

- [ ] Documentation (N/A?)
- [x] Tests
- [x] Typescript definitions updated
- [x] Ready to be merged
      
- [x] Added myself to contributors table
      

I am not too happy about spreading `props` there. In simple cases of a one Provider it's fine, but in the example above it might be confusing what you are supposed to do there.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Maybe the examples can just destructure children instead of spreading all the props. Children is all that's needed right?

**Comment by FredyC** [comment]
> Maybe the examples can just destructure children instead of spreading all the props. Children is all that's needed right?

It's a bit bulkier this way, but I guess there is no other more graceful way without introducing extra complexity.

```jsx
  testHook(callback, {
    wrapper: ({ children }) => (
      <NameContext.Provider value={nameValue}>
        <OtherContext.Provider value={otherValue}>
          {children}
        </OtherContext.Provider>
      </NameContext.Provider>
    )
  })
```

Btw, what about docs? I am not sure how to contribute there... Not even mentioning that `testHook` isn't there at all yet. I assume it's different repo so I should try to handle it in this PR, right?

**Comment by FredyC** [comment]
@kentcdodds Are you ok with ignoring that eslint rule in tests (last commit). If yes and documentation will be tackled later, then it's ready for merge.

**Comment by FredyC** [comment]
@kentcdodds Would not mind contributing, but I do have trouble finding the repo for docs. Would be a good idea to mention that in CONTRIBUTING.

**Comment by kentcdodds** [comment]
> Would be a good idea to mention that in CONTRIBUTING.

Agreed! Would you like to add a note about that. The docs repo is linked in the docs: https://github.com/alexkrolick/testing-library-docs

**Comment by alexkrolick** [comment]
I'd like to do a follow-up PR to add this option to `render`. I'll reopen the issue with a check for the testHook part.

Thanks @FredyC!

**Comment by ThanhPhat1080** [comment]
Hi. Could you guys please let me know where is the docs to see how to implement `testHook`. For now, I try to implement testing with my context but it not work. 
```
const useTestContext = () => {
  return useContext(AccountContext);
};

testHook(
    () => {
      accountState = useTestContext();
    },
    {
      wrapper: () => (
        <BrowserRouter>
          <AccountProvider>
            <AuthenticationForm />
          </AccountProvider>
        </BrowserRouter>
      ),
    },
  );

```
The `accountState` is undefined for now.

**Comment by FredyC** [comment]
@ThanhPhat1080 Yea well, docs are kinda behind on this. I want to dive into that but got some other hurdles on the path. As for your example, you need this.

```jsx
testHook(
    () => {
      accountState = useTestContext();
    },
    {
      wrapper: ({ children }) => (
        <BrowserRouter>
          <AccountProvider>
            <AuthenticationForm>{children}</AuthenticationForm>
          </AccountProvider>
        </BrowserRouter>
      ),
    },
  );
```

It's intuitive much for sure and I am not too happy about it either. I am not sure if it could somehow automagically inject those children there.

**Comment by ThanhPhat1080** [comment]
Thanks @FredyC It work for now, this is my code to let it work 
```js
testHook(
    () => {
      accountState = useTestContext();
    },
    {
      wrapper: ({ children }) => (
        <BrowserRouter>
          <AccountProvider>
            {children}
            <AuthenticationForm />
          </AccountProvider>
        </BrowserRouter>
      ),
    },
  );
```

I have a question. Example my component have button and when fire click on it, it should change the context-value and update UI. I want to test that action and test the UI is updated or not. I tried using `render` but the context-value is not change. So testHook can test it or not?

**Comment by alexkrolick** [comment]
Docs PR for testHook: https://github.com/alexkrolick/testing-library-docs/pull/32

**Comment by alexkrolick** [comment]
@ThanhPhat1080 testHook is meant to test the return value of custom hooks. For testing components that use the hooks, you test them the normal way, with render.

**Comment by ThanhPhat1080** [comment]
Thanks @alexkrolick

**Pull request merged**
