### PR TITLE
 fix(definitions): export correct types for wait and waitForExpect

### PR DESCRIPTION
**Pull request by jday3**
**What**: Updates to `wait` and `waitForExpect` Typescript definitions

**Why**: The types are incorrect - `wait` should not be a default export and `waitForExpect` was missing arguments

**How**: 

**Checklist**:

* [ ] Documentation
* [ ] Tests
* [x] Ready to be merged 
* [x] Added myself to contributors table

### CODE REVIEW

**Comment by tsiq-swyx** [comment]
just writing to say thank you. i use typescript and this fix is exactly what i need to use it.

**Comment by kentcdodds** [comment]
Thanks for the review @tsiq-swyx. I'll go ahead and merge this.

**Comment by tsiq-swyx** [comment]
mind pushing a patch version to npm for this when you get time? my CI thing doesnt like v1.9.3 because of this thing. no rush at all.

**Comment by kentcdodds** [comment]
Hmmm... It should have published a new release automatically. I'm not sure what went wrong. I'll look into it.

**Comment by kentcdodds** [comment]
Ok, 1.9.4 has been published!

**Pull request merged**
