### PR TITLE
Add getAllByTestId & queryAllByTestId helper functions

### PR DESCRIPTION
**Pull request by bahdcoder**
**What**: Add new query capabilities for improved tests

- getAllByTestId
- queryAllByTestId

**Why**: These will include querying for multiple elements rendered in the dom
It will improve usability of the module.

add tests for queryAllByTestId functions
add tests for getAllByTestId function

**How**:

- Added the respective functions in the `queries.js` file
- Added tests for functions in the `__tests__/element-queries.js` file

**Checklist**:

* [ ] Documentation
* [x] Tests
* [x] Ready to be merged 
* [x] Added myself to contributors table

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks for this! However I'm not sure I want to add it. A test ID should normally be unique and identify a single element. I'm not sure if a good use case for having multiple elements with the same ID. There's documentation in the README FAQ about how to make it unique for elements that you iterate over and I feel like that's enough. What do you think?

**Comment by bahdcoder** [comment]
Hey @kentcdodds , Didn't see the README FAQ on iterated items earlier, but now that I have, I totally agree with you about  test ID being unique (Even when raising the pull request I had a very quiet doubt in my mind about this).
I guess this should be closed then. 👍 

Just a little question in my mind. What if I needed to get all the iterated items and count them ? How do you suggest this could be done ? I was thinking using css regular express attribute matching ? 

One last thing, you are a great motivator of mine, and thanks to you (egghead tutorials and blog posts) I have been able to raise my very first ever pull request to an open source. I'm grateful for the opportunity. 🙇  Thanks a lot for your time.

**Comment by lgandecki** [comment]
@bahdcoder how about set a testid on a parent of elements you want to count, and then count the children :-)

**Comment by kentcdodds** [comment]
Hi friends :wave:

Thanks for the discussion here. I think based on this discussion I'll go ahead and close this PR. Maybe someday it'll resurface again. But for now it's easier to say "no" now and bring it back up again in the future than to say "yes" and try to remove it in the future.

Thanks!

**Pull request closed without merging**
