### PR TITLE
chore: center the docs links

### PR DESCRIPTION
**Pull request by alexkrolick**
🤷‍♂️ 

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged
      
- [ ] Added myself to contributors table

### CODE REVIEW

**Comment by weyert** [comment]
Any reason why this has to be removed from the README file? Now you can't refer to the docs while  not having internet e.g. on the airplane :(

**Comment by alexkrolick** [comment]
It's hard to keep in sync in two places - the rtl and dtl docs are already out of sync

You can pull down the repo for the docs if you'd like - it's all markdown

**Comment by kentcdodds** [comment]
We should see what it would take to get the docs on https://devdocs.io and https://kapeli.com/dash and I wonder how hard it would be to make a service worker for the website 🤔

**Comment by alexkrolick** [comment]
https://docusaurus.io/blog/2018/09/11/Towards-Docusaurus-2

Maybe in Docusaurus 2.0

Opening this discussion on the docs repo

**Comment by weyert** [comment]
Never meant to sound negative just wanted to raise an accessibility issue 😇
Trying to synchronise both projects using the Dino definitely makes totally sense :)

**Pull request merged**
